# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161231_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='status',
            field=models.TextField(default='old', max_length=128),
            preserve_default=False,
        ),
    ]
